// signup the user into the database 
POST http://localhost:5001/api/auth/signup
content-type: application/json

{
"name":"Ankit Kaushik 002",
"email":"Ankitkaushik1@gmail.com",
"password": "123123",
"phone":"918930485009"
}

// to verify your account using the 6 word otp you received 
###
POST http://localhost:5001/api/auth/verify
content-type: application/json

{
    "email":"Ankitkaushik@gmail.com",
    "otp":"540451"
}


// to login the user into the database 
###
POST http://localhost:5001/api/auth/login
content-type: application/json

{
    "email":"Ankitkaushik@gmail.com",
    "password":"123123"
}

// to logout the user into the database 
###
POST http://localhost:5001/api/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZjNWY3OTVjOGEwMzBmYmViODllOWEiLCJuYW1lIjoiQW5raXQgS2F1c2hpayAwMDEiLCJlbWFpbCI6IkFua2l0a2F1c2hpa0BnbWFpbC5jb20iLCJpYXQiOjE2ODQ4MjQwNjksImV4cCI6MTY4NDkxMDQ2OX0.5vM4tnFGfuIlf6qorza8ucVY-P88UUhf0OyxVguscOU

// to make an admin into the database
###
POST http://localhost:5001/api/auth/admin?KEY=ankitkaushiksecretkey
content-type: application/json

{
    "name": "testAdmin",
    "email":"testAdmin@gmail.com",
    "password": "1234567",
    "phone":"918930485009"
}


// to create the question into the question bank - authorized only admin
###
POST http://localhost:5001/api/editor/create?_id=64648c377489abe4213ac945
content-type: application/json

{
    "title":"3rd test question ",
    "option":["a","b","c","d"],
    "answer":"a",
    "type":"hard"
}

// to get all the question
###
GET http://localhost:5001/api/editor/get

// get quesetion filtered by the easy 
###
GET http://localhost:5001/api/editor/get/easy

// get quesetion filtered by the medium
###
GET http://localhost:5001/api/editor/get/medium

// get quesetion filtered by the hard
###
GET http://localhost:5001/api/editor/get/hard